region = "West Central US"
resource_group_name = "HelloWorld"
virtual_network_name = "dev-vir-nw"
network_security_group_name = "dev-nwsg"
storage_account_name = "nagap2016"
storage_container_name = "dev-storage-container"
virtual_machine_name = "dev-ubuntu"
