---
 - hosts: all
   sudo: yes
   tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
      notify:
        - restart apache2
    - name: copies the file index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0755
   handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
