---
  -hosts: local
   sudo: yes
   tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest
      notify:
        - restart apache2
   handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
